Fully localized Russian Language  (Author asked to create PR)
e99999/GT-Classic pull request #160
Opened 2021-02-12 14:58 UTC by Skyine918

2021-02-12 16:46 UTC, CrossVas reviewed
Did a check over translation

2021-02-12 16:46 UTC, CrossVas commented on src/main/resources/assets/gtclassic/lang/ru_ru.lang
> +tooltip.gtclassic.matterfabricator1=Теперь обновлен, с внутреним баком для жидкостей!!!
Я бы использовал "улучшен" вместо "обновлён"

2021-02-12 16:46 UTC, CrossVas commented on src/main/resources/assets/gtclassic/lang/ru_ru.lang
> +tooltip.gtclassic.uumassembler0=Устали от ручного крафта из материи? Не смотрите дальше.
Look no further говорит о том, что вам ничего другого не нужно, вы нашли то, что искали, то что вам необходимо.
"Не смотрите дальше" я бы заменил на "Вы нашли то, что искали."

Как Вам вариант "Устали вручную крафтить вещи из материи?" для первой части?

2021-02-12 16:46 UTC, CrossVas commented on src/main/resources/assets/gtclassic/lang/ru_ru.lang
> +tooltip.gtclassic.disassembler0=Раскрафт с шансом 80% возвращения ресурсов
"Раскрафт"? "Разбирает" подходит лучше.

2021-02-12 16:46 UTC, CrossVas commented on src/main/resources/assets/gtclassic/lang/ru_ru.lang
> +tooltip.gtclassic.bedrockminer0=Копает руды бедроке, в квадрате 5х5 под ним
"Копает бедроковые руды радиусом в 5 блоков от него"

2021-02-12 16:46 UTC, CrossVas commented on src/main/resources/assets/gtclassic/lang/ru_ru.lang
> +tooltip.gtclassic.bedrockminer1=Должен стоять на руде в бедроке
"на бедроковой руде"? Как Вам такой вариант?

2021-02-12 16:46 UTC, CrossVas commented on src/main/resources/assets/gtclassic/lang/ru_ru.lang
> +tooltip.gtclassic.playerdetector2=Нажатие с шифтом пустой руком чтобы сменить режим
"Нажмите шифт и пустой рукой, чтобы сменить режим"
или можно оставить Ваш вариант, только "пустой рукой", у Вас опечатка.

2021-02-12 16:46 UTC, CrossVas commented on src/main/resources/assets/gtclassic/lang/ru_ru.lang
> +tooltip.gtclassic.mobrepeller0=Не даёт появляться агресивным существам,
Предотвращает спавн агрессивных мобов
или вместо "спавн" можно использовать "появление"

2021-02-12 16:46 UTC, CrossVas commented on src/main/resources/assets/gtclassic/lang/ru_ru.lang
> +tooltip.gtclassic.energytransmitter1=Используй флеш-накопитель чтобы установить целевую точку.
"Используйте"

2021-02-12 16:46 UTC, CrossVas commented on src/main/resources/assets/gtclassic/lang/ru_ru.lang
> +tooltip.gtclassic.charcoalpit0=Трансформирует бревнав блоки сгоревшей древесины,
опять опечатка

2021-02-12 16:46 UTC, CrossVas commented on src/main/resources/assets/gtclassic/lang/ru_ru.lang
> +tooltip.gtclassic.charcoalpit1=Должен стоять на бревне,
Должен стоять "над" брёвнами\бревном, а не "на" бревне

2021-02-12 16:46 UTC, CrossVas commented on src/main/resources/assets/gtclassic/lang/ru_ru.lang
> +tooltip.gtclassic.dragoneggenergysiphon1=Трофей должен быть наверху Сифона.
Должен быть "над" сифоном

2021-02-12 16:46 UTC, CrossVas commented on src/main/resources/assets/gtclassic/lang/ru_ru.lang
> +tooltip.gtclassic.tesseractslave1=Используй флеш-накопитель чтобы выбрать точку тессеракта.
"Используйте"

2021-02-12 16:46 UTC, CrossVas commented on src/main/resources/assets/gtclassic/lang/ru_ru.lang
> +tooltip.gtclassic.translocator0=Перемещает предметы с точки А в точку Б
Перемещает "из" точки А в точку Б

2021-02-12 16:46 UTC, CrossVas commented on src/main/resources/assets/gtclassic/lang/ru_ru.lang
> +tooltip.gtclassic.buffersmall0=Небольшая настраиваемая Воронка wс встроеным Энергопроводом
Опечатка, а так-же "со встроенным"

2021-02-12 16:46 UTC, CrossVas commented on src/main/resources/assets/gtclassic/lang/ru_ru.lang
> +tooltip.gtclassic.translocatorfluid0=Перемещает жидкости с точки А в точку Б
"из" точки А

2021-02-12 16:46 UTC, CrossVas commented on src/main/resources/assets/gtclassic/lang/ru_ru.lang
> +tooltip.gtclassic.flintmortar0=Выполняет 'принимаемую' Работу превращения вещей в пыль...
Выполняет "приемлемую" задачу по превращению вещей в пуль.

2021-02-12 16:46 UTC, CrossVas commented on src/main/resources/assets/gtclassic/lang/ru_ru.lang
> +tooltip.gtclassic.redstonetransmitter1=используй флеш-накопитель чтобы установить целевую точку.
Используйте

2021-02-12 16:46 UTC, CrossVas commented on src/main/resources/assets/gtclassic/lang/ru_ru.lang
> +tooltip.gtclassic.blockextender0=Реле прикрепляет инвентари и баки
Relays - глагол. Следовательно правильнее будет использовать
"Передаёт содержание прилегающих инвентарей и баков"

2021-02-12 16:46 UTC, CrossVas commented on src/main/resources/assets/gtclassic/lang/ru_ru.lang
> +tooltip.gtclassic.blockextender1=Не может быть прикреплен к другим удлинителям!
"Не может работать рядом с другим расширителем"

2021-02-12 16:46 UTC, CrossVas commented on src/main/resources/assets/gtclassic/lang/ru_ru.lang
> +tooltip.gtclassic.itemfilter0=Фильтр, который также буферизует элементы!
"который так-же сохраняет элементы в буфере"

2021-02-12 16:46 UTC, CrossVas commented on src/main/resources/assets/gtclassic/lang/ru_ru.lang
> +tooltip.gtclassic.displayscreen1=Используй флеш-накопитель чтобы установить целевую точку.
Используйте

2021-02-12 16:46 UTC, CrossVas commented on src/main/resources/assets/gtclassic/lang/ru_ru.lang
> +button.gtclassic.magicabsorber2=Впитываниее энергии портала энда
Опечатка

2021-02-12 16:46 UTC, CrossVas commented on src/main/resources/assets/gtclassic/lang/ru_ru.lang
> +button.gtclassic.magicabsorber3=Предупреждение только одно на портал!
Предупреждение!!! Только одно\один на портал!!!

2021-02-12 16:46 UTC, CrossVas commented on src/main/resources/assets/gtclassic/lang/ru_ru.lang
> +button.gtclassic.worktable0=Перенести предметы крафтовой сетки в инвентарь игрока
"предметы с сетки крафта"

2021-02-12 16:46 UTC, CrossVas commented on src/main/resources/assets/gtclassic/lang/ru_ru.lang
> +button.gtclassic.worktable1=Переместите предметы сетки крафта в основной инвентарь
"Перенести предметы с сетки крафта в основной инвентарь"
Следует придерживаться единой формулировки. Если в первом случает Вы использовали "Перенести", то тут не должно быть "Переместите"

2021-02-12 16:46 UTC, CrossVas commented on src/main/resources/assets/gtclassic/lang/ru_ru.lang
> +button.gtclassic.buffer4=Игнорировать Nbt
"NBT"

2021-02-12 16:46 UTC, CrossVas commented on src/main/resources/assets/gtclassic/lang/ru_ru.lang
> +button.gtclassic.rockbreaker=Используйте красный камень или кварц для модуляции типов камня.
"Используйте редстоун или кварц, чтобы изменить породу камня"
Везде "редстоун", а тут вдруг "красный камень"

2021-02-12 17:56 UTC, amegasterr commented on src/main/resources/assets/gtclassic/lang/ru_ru.lang
> +tile.gtclassic.magicenergyconverter.name=Магический преабразователь энергии
Благодарю за критику и редакцию

2021-02-12 20:55 UTC, Skyine918 commented
I have fixed some entries with new commit. Feel free to offer improvements

2021-02-12 21:25 UTC, CrossVas commented
Не совсем понятно, почему вы проигнорировали мои замечания насчёт "Раскрафт". 
Так-же комментарий к строкам 261, 275, 313, 325 были игнорированы.

2021-02-12 21:48 UTC, Skyine918 commented
@CrossVas sorry it looks like I have missed it because they were hidden. It is the first time I create merge request on github. I will review and commit new changes on this saturday/sunday.

2021-02-14 19:27 UTC, Skyine918 commented
I'm sorry for the delay, I fixed all entries that I missed, please check when you have time

2021-02-14 20:11 UTC, CrossVas requested changes
A few more fixes and You are good to go with this translation. 
Also I noticed that in some cases You used "Shift-click" and in others didn't. I'm not sure if this is so important to fix, so the decision to change or not is yours.

Ещё несколько исправлений и Ваш перевод полностью готов.
Ещё я заметил, что в некоторых местах Вы использовали вариант "Шифт-клик", а в некоторых без "-", не знаю, значительная ли эта деталь, уже на Ваше усмотрение.

2021-02-14 20:11 UTC, CrossVas commented on src/main/resources/assets/gtclassic/lang/ru_ru.lang
> +tooltip.gtclassic.blockextender0=Передаёт содержание прилегающих инвентарей и баков
Содержание -> содержимое

Моя ошибка.

2021-02-14 20:40 UTC, Skyine918 commented
Fixed now

2021-02-14 20:41 UTC, CrossVas commented
Строка 322.
"Содержание" поменять на "содержимое".

2021-02-14 20:47 UTC, CrossVas commented
Gut

2021-02-15 23:11 UTC, merged